### ISSUE TITLE
NIH Lform not working in ionic mobile application

### ISSUE THREAD

**Issue by manojmohanan23** [lhncbc/lforms#1]
We need to use the LHC forms in an ionic framework. It seems some conflicts with ionic JS and ionic CSS while including library files of lforms. The issue we faced is that the drop down selection will not apply to HTML value. Anybody please suggest a solution, if you have already used lforms in an ionic framework.

Thanks

**Comment by plynchnlm** [comment]
Could you provide some more information about the error?  What do you mean by "the drop down selection will not apply to HTML value"?  After you pick from a list, the value does not show up in the field?  Is there an error message in the developer tools console?  Is there someplace we can see the problem?

We don't have experience with the ionic framework, but if there is something we can adjust to help resolve the incompatibility, we would be happy to do so.

**Comment by manojmohanan23** [comment]
There is no console error, in mobile resolution, no binding happens, that means when we select an option from the drop-down can't get selected option value.

**Comment by plynchnlm** [comment]
Okay, some questions:

1) "Only in mobile resoution" but "also in the browser".  Are you saying that if you resize a browser window down to the size of a cell phone, the binding stops working?

2) Which version of LForms are you using?

3) Which browser (and version) does the problem happen in?

4) Our demo web site, https://lhc-forms.lhc.nlm.nih.gov/, has a "Load form" button which will let you upload your own form, and it will open in a new window.  Could you see if the problem can be reproduced there, if you make the window small?

5)  If you can reproduce the problem in (4), could you send us the form definition so we can try it?

6) When you see the problem, does the output of LForms.Util.getUserData(null, true, true, true) or LForms.Util.getFormData() contain the data selected from the list?  It should show up as a "value" attribute on the question item.

**Comment by plynchnlm** [comment]
Closing due to lack of response.  If you still need assistance, feel free to open a new issue.
