### ISSUE TITLE
Validation rule definition in a demo form

### ISSUE THREAD

**Issue by dattachandan** [lhncbc/lforms#10]
Is there any example of how to specify and validate field rules in any of the elements of the SDC profile?
http://hl7.org/fhir/us/sdc/sdc-questionnaire.html
https://github.com/lhncbc/lforms-fhir-app

For example, if we have a string element in a combo-box and we want to specify the minLength/maxLength or a regex pattern that will also be used represented in the form builder  generated code.

`
"type": "choice",
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-itemControl",
              "valueCodeableConcept": {
                "coding": [
                  {
                    "system": "http://hl7.org/fhir/questionnaire-item-control",
                    "code": "Combo-box",
                    "display": "Combo-box"
                  }
                ],
                "text": "Combo-box"
              }
            }
          ]
`

**Comment by plynchnlm** [comment]
First, be advised that:
1) There is a new version of SDC being balloted (ballot closing on April 29th) at http://hl7.org/fhir/uv/sdc/2019May/index.html
2) Our item-control codes that we output are outdated (or maybe just wrong).  I was actually planning to work on fixing that today.

Now, to your question.  If I understood correctly, you are using the LHC Form Builder (https://lhcformbuilder.nlm.nih.gov/) to create a form, and you want to add something like minLength.  Steps for doing that:

1) From the left pane, select the item to which you want to add the field validation.
2) In the middle pane for editing the item, there are two tabs, "Build Basic Properties" and "Build Advanced Properties."  Click the advanced one.
3) Change the value of "Add restrictions" to "Yes".  The form builder calls field validation rules "restrictions".  A new section should open under than question when you choose "Yes".
4) Under "type" select "Minimum Length"
5) Enter the length you want in "Value".
6)  In the pane on the right, which has the form preview, click the "JSON Output" tab.  You should see that an extension has been added to the item like:
      "extension": [
        {
          "url": "http://hl7.org/fhir/StructureDefinition/minLength",
          "valueInteger": 3
        }

**Comment by dattachandan** [comment]
Thanks. 

I can see it now.

![image](https://user-images.githubusercontent.com/2154248/56864777-8ab01400-6a1a-11e9-8a6c-daa615ae2465.png)


I tried SMART-on-FHIR app client here to understand the form definition language and the FHIR questionnaire response which seem to be a combination of the form UI and the logic: https://apps.smarthealthit.org/app/lforms-questionnaire-app

- Is there any example code of pre-populating a form defined using the json Form Definition Format(https://github.com/lhncbc/lforms/blob/master/form_definition.md) from a FHIR server and validating the response on the form using the validation rules defined? Also is it possible to match a FHIR server response to a form definition section such as tabular medication lists? I started building a form but not sure how to specify that a given section has to be pre-populated from a given FHIR resource. 

![image](https://user-images.githubusercontent.com/2154248/56864950-8258d880-6a1c-11e9-8eb2-5dc36779f8f9.png)

![image](https://user-images.githubusercontent.com/2154248/56865098-36a72e80-6a1e-11e9-9248-e11d9a522cad.png)

`
{
  "name": "NewTestFormCD",
  "items": [
    {
      "question": "Patient Demographics",
      "questionCodeSystem": "Custom",
      "questionCode": "[Q1]",
      "questionCardinality": {
        "min": "1",
        "max": "1"
      },
      "header": true,
      "editable": "1",
      "answerCardinality": {
        "min": "0",
        "max": "1"
      },
      "items": [
        {
          "question": "Patient Name",
          "questionCodeSystem": "Custom",
          "questionCode": "[Q1.1]",
          "questionCardinality": {
            "min": "1",
            "max": "1"
          },
          "header": true,
          "editable": "1",
          "answerCardinality": {
            "min": "0",
            "max": "1"
          },
          "displayControl": {
            "questionLayout": "horizontal"
          },
          "items": [
            {
              "question": "Patient Name Prefix",
              "questionCodeSystem": "Custom",
              "questionCardinality": {
                "min": "1",
                "max": "1"
              },
              "header": false,
              "editable": "1",
              "answerCardinality": {
                "min": "1",
                "max": "1"
              },
              "dataType": "CNE",
              "answers": null,
              "defaultAnswer": "Mr"
            },
            {
              "question": "Patient First Name",
              "questionCodeSystem": "Custom",
              "questionCardinality": {
                "min": "1",
                "max": "1"
              },
              "header": false,
              "editable": "1",
              "answerCardinality": {
                "min": "0",
                "max": "1"
              },
              "dataType": "ST"
            },
            {
              "question": "Patient Last Name",
              "questionCodeSystem": "Custom",
              "questionCardinality": {
                "min": "1",
                "max": "1"
              },
              "header": false,
              "editable": "1",
              "answerCardinality": {
                "min": "0",
                "max": "1"
              },
              "dataType": "ST"
            },
            {
              "question": "Patient Name Postfix",
              "questionCodeSystem": "Custom",
              "questionCardinality": {
                "min": "1",
                "max": "1"
              },
              "header": false,
              "editable": "1",
              "answerCardinality": {
                "min": "0",
                "max": "1"
              },
              "dataType": "ST"
            }
          ]
        },
        {
          "question": "Patient Office Telephone",
          "questionCodeSystem": "Custom",
          "questionCardinality": {
            "min": "1",
            "max": "1"
          },
          "header": false,
          "editable": "1",
          "answerCardinality": {
            "min": "0",
            "max": "1"
          },
          "dataType": "ST"
        },
        {
          "question": "Patient Home Telephone",
          "questionCodeSystem": "Custom",
          "questionCardinality": {
            "min": "1",
            "max": "1"
          },
          "header": false,
          "editable": "1",
          "answerCardinality": {
            "min": "0",
            "max": "1"
          },
          "dataType": "ST"
        }
      ]
    },
    {
      "question": "Patient Medications",
      "questionCodeSystem": "Custom",
      "questionCardinality": {
        "min": "1",
        "max": "1"
      },
      "header": true,
      "editable": "1",
      "answerCardinality": {
        "min": "0",
        "max": "1"
      },
      "items": [
        {
          "question": "Patient Regular Medications",
          "questionCodeSystem": "Custom",
          "questionCardinality": {
            "min": "1",
            "max": "1"
          },
          "header": true,
          "editable": "1",
          "answerCardinality": {
            "min": "0",
            "max": "1"
          }
        },
        {
          "question": "Patient PRN medications",
          "questionCodeSystem": "Custom",
          "questionCardinality": {
            "min": "1",
            "max": "1"
          },
          "header": true,
          "editable": "1",
          "answerCardinality": {
            "min": "0",
            "max": "1"
          }
        }
      ]
    }
  ]
}
`

- Does the FHIR questionnaire  or the Form Definition Format allow more complex UI controls to be defined such as a DatePicker (as shown below for DoB) or RadioButtons? Then on selecting an option on a radio button, it displays further options as shown below when the Yes option in cardiovascular disease is selected and error options when user selection is not correct.

![image](https://user-images.githubusercontent.com/2154248/56864794-d793ea80-6a1a-11e9-9e52-2ba420731b78.png)
![image](https://user-images.githubusercontent.com/2154248/56864845-67399900-6a1b-11e9-944e-bdd73288941c.png)

![image](https://user-images.githubusercontent.com/2154248/56864859-a10a9f80-6a1b-11e9-82b2-c8c66cd10845.png)

![image](https://user-images.githubusercontent.com/2154248/56864904-27bf7c80-6a1c-11e9-8759-fdfbdd3e1313.png)

- Is it possible for the form JSON definition to define selection of files or display pre-populated mimetypes from a FHIR server
![image](https://user-images.githubusercontent.com/2154248/56864888-09598100-6a1c-11e9-9f97-f265c2fb4c72.png)


- Is there a converter for the Form Definition Format-> FHIR questionnaire as well as an api as it is in the form builder tool?
![image](https://user-images.githubusercontent.com/2154248/56864764-4fade080-6a1a-11e9-9bfd-863b64af3d0d.png)

**Comment by plynchnlm** [comment]
If you are interested in FHIR and FHIR servers, I would not advise working with the LForms internal form definition format, which predates the FHIR support we've added.

>     * Is there any example code of pre-populating a form defined using the json Form Definition Format(https://github.com/lhncbc/lforms/blob/master/form_definition.md) from a FHIR server and validating the response on the form using the validation rules defined?

Prepopulation is only support is only available for FHIR Questionnaire, and we have not yet added those settings to the Form Builder.  So, the path would be to first build a form using the form builder, then export it as FHIR Questionnaire, version R4, (possibly saving that to a FHIR server, but keep your own copy), and then editing the JSON to add the FHIR prepopulation stuff.

Form population is described here: http://hl7.org/fhir/uv/sdc/2019May/populate.html

At present, LForms supports observation-based prepopulation, and part of the FHIRPath-based prepopulation (launchContext, initialExpression, variable, and calculatedExpression).  The only FHIR queries that happen in LForms are in launchContext and observationLinkPeriod, and although launchContext can provide the patient, there isn't yet in LForms support getting to other resources like Medication.  Basically, we can pull in information about the patient resource, and from the patient's observations, and we can do calculations on those, but that is as far as we have gotten to date.

>     * Does the FHIR questionnaire  or the Form Definition Format allow more complex UI controls to be defined such as a DatePicker (as shown below for DoB) or RadioButtons?

Yes.  Radio buttons and date pickers can be created by selected the appropriate data type in the item's "type" field in the form builder.

>     * Then on selecting an option on a radio button, it displays further options as shown below when the Yes option in cardiovascular disease is selected and error options when user selection is not correct.

The first could be done by adding skip logic (under "advanced properties", see "show logic") for the checkbox question so that it is hidden until the user chooses "yes" in the previous question.

Although I have not tested a required field with checkboxes, I would expect LForms to only complain (as with string required fields) if the user field enters a value and then changes it to blank.

We don't yet support selected files for inclusion in the response.  (FHIR does, but we haven't gotten to it yet.)

We don't have an online converter (except the Form Builder) but if you had a collections of form definitions in our internal format, you could use the LForms APIs to convert them to FHIR... although now that I think about it, you might have to do that in a browser.  Although LForms in an npm package, I haven't tried loading into Node.js for server side processing.

**Comment by dattachandan** [comment]
Thanks for those responses.

Is there any work on a lform framework with possible integration with standard UI JS libs such as react or angular so that complex biz logic forms can be built and represented with the FHIR questionnaire and then programmed using that framework. For example, controls for selecting more medications on some biz logic being true or on a button click? The FHIR questionnaire now can represent some of the UI components and the data model, but is there any ongoing work  for a reusable backend framework to help developers build apps for app stores such as SMART-on-FHIR for readily consuming FHIR resources from supported FHIR servers?

![image](https://user-images.githubusercontent.com/2154248/57274923-e0f31600-70f0-11e9-8486-1fd24bd9431a.png)

**Comment by plynchnlm** [comment]
Our focus at present is on improving support for the SDC Questionnaire specification, which includes [FHIRPath-popoulation](http://hl7.org/fhir/uv/sdc/2019May/populate.html#path-pop) and [definition-based extraction](http://hl7.org/fhir/uv/sdc/2019May/extraction.html#definition-extract), which would handle your use case of showing a patient's medication records and allowing edits.

**Comment by dattachandan** [comment]
Thanks for that. Will wait for the ballot review and some samples then
