### ISSUE TITLE
Support for preferredTerminologyServer 

### ISSUE THREAD

**Issue by hivanov** [lhncbc/lforms#105]
Can you please support the following extension: [http://build.fhir.org/ig/HL7/sdc/StructureDefinition-sdc-questionnaire-preferredTerminologyServer.html](preferredTerminologyServer)

It's about adding a preferred terminology server when doing value set expansions. Can have more than one such server.
There are multiple reasons for this:
1. According to HL7 Terminology WG, value sets need to always be expanded;
2. Not all terminology servers contain all the value sets, or can expand them.
3. Currently, all of the commercial FHIR Cloud Servers (Google, Microsoft, Amazon), do not support terminology, and don't plan on adding such support.

**Comment by plynchnlm** [comment]
This is supported, but with the URI mentioned in this tracker item: https://jira.hl7.org/browse/FHIR-23977, which did not get applied before the SDC version was published.  So, if you are able to use the URI http://hl7.org/fhir/StructureDefinition/terminology-server you should find it working.  We are also planning to add support for the published URI, but haven't gotten to it yet.

**Comment by plynchnlm** [comment]
This is fixed in 32.2.0.
