### ISSUE TITLE
Configuration option to prevent appending score value to answer options.

### ISSUE THREAD

**Issue by sjpadgett** [lhncbc/lforms#116]
I would request to have a configuration option to prevent a scoring value appended to answer options.
Since when using numeric values as answers the presentation to users is confusing.

Recommend this is off by default.

**Comment by sjpadgett** [comment]
@plynchnlm 
How is best way to implement this option? I don't understand why appending an answer score to answer item is there in the first place. IMO it should be removed however if it is going to be an option could you point me where in code I should add then I'll put up a P.R.

**Comment by plynchnlm** [comment]
Thanks for offering, but for this issue there is no need-- we have a pull request under review internally.  It will probably be out within a couple of weeks at most.  The score will be present by default, but there will be an option you can pass in to LForms.Util.addFormToPage which will remove it.

**Comment by sjpadgett** [comment]
Okay thanks. I'll just continue to patch out for my core project which btw is working well on 33.1.2 so far.  I had an issue with the ResizeObserver starting after the 33.? refactor which seems to be resolved in 33.1.2.
My forms using FHIR Paths are working very well and have a noticeable speed up on load in recent version so thanks for that.

**Comment by plynchnlm** [comment]
The speed up was in 33.1.2-- glad to see hear that fix is helping your use case.

**Comment by lhcye** [comment]
This feature is now in v33.2.0.

**Comment by sjpadgett** [comment]
Thanks guys, appreciate the change.

**Comment by sjpadgett** [comment]
I just tested this using the release 33.2.0 download and does not work for me.
I'm adding `"displayScoreWithAnswerText": false` to option array passed to `LForms.Util.addFormToPage()`

**Comment by plynchnlm** [comment]
It should be an "options" object, not an array.

**Comment by sjpadgett** [comment]
Correct on the object which is what I use however, I cleared browser cache and it is working.
I'm a dummy as this is first thing I tell folks using my site. So sorry and will close issue as resolved with my thanks!

**Comment by plynchnlm** [comment]
No problem!  We all get tripped up by browser caches.  I am glad it is working for you.

**Comment by sjpadgett** [comment]
Are you guys planning another release soon as I want to release this in our next patch release in a couple weeks?

**Comment by plynchnlm** [comment]
Well, we make releases as we fix things or add features.  I would expect an update roughly every couple of weeks.

**Comment by sjpadgett** [comment]
Okay thanks. Maybe I figure out something for you guys to do!:) kidding...

**Comment by plynchnlm** [comment]
We have a very long backlog, unfortunately, but we try to take users' needs into account when prioritizing.  Glad to hear you are recommending use of FHIRPath.
