### ISSUE TITLE
Building the Lforms library as npm package on local to test with host application.

### ISSUE THREAD

**Issue by nikhil-ht** [lhncbc/lforms#118]
Hi, Team I am working with Lforms version (29.3.1), Which is angular js based.

I Need to build the Lfroms library locally as an npm package and test it with the host application.
When I am building the Lforms library with npm run build It is creating a web-component structure in the dist,
It is not creating the npm package Since I have integrated the npm package in my Host application. And web component structure not works with the host app.

Can you please let me know How I Can build the Lforms as an npm package instead of a web component and use it in our host app?

**Comment by plynchnlm** [comment]
Try "npm pack".

**Comment by nikhil-ht** [comment]
Thank You !!

**Comment by plynchnlm** [comment]
You are welcome!
