### ISSUE TITLE
Radio buttons are not checked within a vertical table

### ISSUE THREAD

**Issue by Harown** [lhncbc/lforms#119]
_Given_: 

- a questionnaire with a vertical table group and choice items that are rendered as radio buttons
- a response with answers

_Expected_:

- checked radios after merging the response into the questionnaire
- radios within a vertical table styled as radios outside of such table (ant design)

_Actual_:

- radios are not checked
- radios are pure HTML elements instead of ant radios like radios outside of a vertical table

JSFiddle: https://jsfiddle.net/Harown/5z4tsLv0/15/

Some observations:

- removing the vertical table results in ant radios that are checked as expected
- removing the `display` attribute in the answers also results in checked radios - even within the vertical table
- our questionnaire author can't use a more appropriate select box here instead of radios since the questionnaire will be used for web and paper 

Dunno if it is a bug in lforms or something fraud with the questionnaire spec. 🙂

**Comment by plynchnlm** [comment]
It is a bug.  Thank for your for this report and the JSFiddle.  We are looking into it.
