### ISSUE TITLE
Not able to use lform NPM package in angular app.

### ISSUE THREAD

**Issue by ddjain** [lhncbc/lforms#123]
We are using angular Version 14

Trying to use Lform package but its giving lform modules not defined error

Can you please provide steps to Use NPM package in angular.

**Comment by ddjain** [comment]
- We have follows above steps of Readme to integrate Lforms in angular project, Now app has started but throwing below error one time in console while app is loading.

- Below is SS of Console window when angular app launches

![DeepinScreenshot_select-area_20230403171019](https://user-images.githubusercontent.com/17905734/229499057-b587efe5-b726-45f5-aa24-3a1c4e48fdb5.png)

- Also Tests case fails while running `npm run test` in our angular app configured with lforms.

- Attaching below SS for same, can please provides steps to fix these failures or suppress in our angular application.

![DeepinScreenshot_select-area_20230403170312](https://user-images.githubusercontent.com/17905734/229497557-6c2e960a-54a6-4b0e-ac94-c0b94c8e9be1.png)

**Comment by plynchnlm** [comment]
I am assuming the "npm run build" you are referring is not the lforms one, but the one in your own project using lforms.  Please make sure you are importing lforms, but are including it via script tags as per the note at http://lhncbc.github.io/lforms/#npmInstall.  Your script tags can point to your local copy of the lforms files.
