### ISSUE TITLE
0 value for number types in response is ignored

### ISSUE THREAD

**Issue by Harown** [lhncbc/lforms#135]
_Given_: 

A questionnaire with an integer question and a response with value `0`.

_Expected_:

Calling `mergeFHIRDataIntoLForms` renders the `0` into the question input.

_Actual_:

Calling `mergeFHIRDataIntoLForms` ignores the `0` and puts nothing into the question input. 

Tested version:

- 30.0.0
- 34.0.2 (latest)

Fiddle: https://jsfiddle.net/axk57f4L/1/ 
You can set the `valueInteger` to any integer - works ... but not for `0`. 

This is not restricted to `integer` types but also to `decimal` and maybe some more number types.

Is this a bug or intended behaviour?

Thanks!

**Comment by lhcye** [comment]
It is indeed a bug. It's fixed in the next version, which will be releases soon.

**Comment by lhcye** [comment]
It is fixed in v34.0.3.

**Comment by Harown** [comment]
Great, thank you for the quick fix.
