### ISSUE TITLE
Error on library import: Uncaught TypeError: Cannot read properties of null (reading 'appendChild')

### ISSUE THREAD

**Issue by alopezo** [lhncbc/lforms#140]
Hi, 

In an angular 15 app, I'm importing like this:

 <link rel="stylesheet" href="https://clinicaltables.nlm.nih.gov/lforms-versions/34.3.1/webcomponent/styles.css">
  <script src="https://clinicaltables.nlm.nih.gov/lforms-versions/34.3.1/webcomponent/lhc-forms.js"></script>

I declare var LForms: any; in typing.d.ts

And I get this error while the library is being imported: 

screenReaderLog.js:23 Uncaught TypeError: Cannot read properties of null (reading 'appendChild')
    at new Y.ScreenReaderLog (screenReaderLog.js:23:23)

![image](https://github.com/lhncbc/lforms/assets/4990842/2baee1f5-4da3-402b-8f3c-f27e0100b602)

**Comment by alopezo** [comment]
Fixed, it was related to not waiting for the DOM to be ready, I'm now importing the library within the component, in the OnInit event:

loadScript() {
    const script = document.createElement('script');
    script.src = 'https://clinicaltables.nlm.nih.gov/lforms-versions/34.3.1/webcomponent/lhc-forms.js'; // Replace with the actual URL of your JS library
    script.onload = () => {
      const script2 = document.createElement('script');
      script2.src = 'https://clinicaltables.nlm.nih.gov/lforms-versions/34.0.0/fhir/R4/lformsFHIR.min.js'; // Replace with the actual URL of your JS library
      script2.onload = () => {
        // Script has loaded
        // Initialize or use the library here, if necessary
      };
      document.head.appendChild(script2);
    };
    document.head.appendChild(script);

  }

**Comment by plynchnlm** [comment]
I am glad you found a workaround, though I am puzzled as to why it was necessary.  The NLM Form Builder (https://lhcformbuilder.nlm.nih.gov/) loads in the lforms files via script tags.  Anyway, the important things is that you have it working.
