### ISSUE TITLE
In repeat questions, SNOMED Answer valuesets are not rendered in the second repetition

### ISSUE THREAD

**Issue by alopezo** [lhncbc/lforms#141]
The form is designed in this way, where the "previous delivery" group is repeating=true :
![image](https://github.com/lhncbc/lforms/assets/4990842/736495a4-880c-4c8b-83c8-63b443ecf4ea)

And renders like this when adding the second delivery:
![image](https://github.com/lhncbc/lforms/assets/4990842/6fa09a36-ef06-4334-a9c7-2effd5c76b52)

Thanks!

**Comment by plynchnlm** [comment]
This was fixed in version 35.0.2 of lforms, though that fix did not make it into the NLM Form Builder until more recently.  I have tried this scenario in the NLM Form Builder, and it looks to me like this is fixed now.

**Comment by alopezo** [comment]
Thanks! it is fixed
