### ISSUE TITLE
UI issue in dropdown options list when resizing the window

### ISSUE THREAD

**Issue by vigneshkv23** [lhncbc/lforms#144]
Hello,

Thanks in advance.

When resizing the dropdown after clicking on the dropbox option. Dropdown option position is not moving below the dropdown.
This issue exists in the demo page and in the lforms package.

questionnaire resource used- [Q Valid.json](https://github.com/lhncbc/lforms/files/14328971/Q.Valid.json)

Please find the screenshot from the lforms package integrated to Angular 12 application and gif from the lhcforms.nlm.nih.gov

![lforms-issue](https://github.com/lhncbc/lforms/assets/27065082/eb7d4155-13ff-4869-923e-2258265a2db3)
<img width="780" alt="image" src="https://github.com/lhncbc/lforms/assets/27065082/f9ebebfe-52b6-45c0-97aa-257c654a7aac">
<img width="785" alt="image" src="https://github.com/lhncbc/lforms/assets/27065082/ae2be4fe-51d1-4c24-9ed6-b4f310b99af1">

**Comment by plynchnlm** [comment]
Thanks for reporting this.  We will look into into fixing it.

**Comment by jcy1225** [comment]
This issue is fixed with the latest version.
