### ISSUE TITLE
Validation popover addresses wrong answer in repeatable item

### ISSUE THREAD

**Issue by Harown** [lhncbc/lforms#146]
### Given

A questionnaire with an repeatable item with an invalid first answer. More answer inputs are created by clicking the "Add another row of" button.

### Expected

The validation popover should address the first answer.

### Actual

The validation popover addresses the lowest (bottommost?) answer:

![image](https://github.com/lhncbc/lforms/assets/28299979/fba10b27-a6e5-432d-ab05-72b968752708)

### Tested version

35.0.4 (latest)

[Fiddle: https://jsfiddle.net/axk57f4L/1/](https://jsfiddle.net/7bxnLo8e/)

Thanks!

**Comment by plynchnlm** [comment]
This is fixed as of 36.0.2.
