### ISSUE TITLE
Preview in multiple columns

### ISSUE THREAD

**Issue by DaniArj1980** [LHNCBC/lforms#148]
Good morning,

Would there be a way that in the questionnaire preview several items could be displayed in the same row, for the entire questionnaire. For example, two items per row.

Regards thank you very much

**Comment by plynchnlm** [comment]
Are you asking about having answer options (radio buttons and checkboxes) appearing in multiple columns, or having the questions themselves appearing in multiple columns?

**Comment by DaniArj1980** [comment]
I am wondering if it is possible to display several questions in the same row appearing in several columns, for example that name and surname are displayed in the same row.

Regards thank you very much

**Comment by plynchnlm** [comment]
The only way I can think of doing that is put each row of questions into a group, like:
https://jsfiddle.net/nc8sr1Lg/1/
