### ISSUE TITLE
questions about the functionality of LHC forms with repeating elements

### ISSUE THREAD

**Issue by GitHubUNCStudent** [lhncbc/lforms#17]
Hi,

I have some questions about the standard functionality of LHC forms with respect to numbering of items in the questionnaire response when there are repeating elements.

For instance, see our sample questionnaire response (available at https://lforms-fhir.nlm.nih.gov/baseR4/QuestionnaireResponse/355762/_history/1)

If the person answering the questionnaire inputs these answers for the repeating element of Risks:

**(for the first risk):**
Physical risk
Pain from injections
Effects will become apparent during the study
No

**(for the second risk):**
Physical risk
Lowered immunity from the medication
Effects will become apparent during the study
Yes

**(for the third risk):**
Psychological or Emotional
Stress over the effects of the medication
Effects will become apparent during the study
No

**(for the fourth risk):**
Physical risk
Liver damage from the medication
Effects will become apparent during the study
Yes

**(for the fifth risk):**
Physical risk
Cancer developing after treatment with the medication
Effects may become apparent many years after the study
Yes 

what we are seeing is that the numbering of the link IDs is not making the answers unique, because the link IDs are repeating whenever a new risk is added, as in:

**(for the first risk):**
linkId: "/1/1.1"  Physical risk
linkId: "/1/1.2"  Pain from injections
linkId: "/1/1.3"  Effects will become apparent during the study
linkId: "/1/1.4"  No

**(for the second risk):**
linkId: "/1/1.1"  Physical risk
linkId: "/1/1.2"  Lowered immunity from the medication
linkId: "/1/1.3"  Effects will become apparent during the study
linkId: "/1/1.4"  Yes

**(for the third risk):**
linkId: "/1/1.1"  Psychological or Emotional
linkId: "/1/1.2"  Stress over the effects of the medication
linkId: "/1/1.3"  Effects will become apparent during the study
linkId: "/1/1.4"  No

**(for the fourth risk):**
linkId: "/1/1.1"  Physical risk
linkId: "/1/1.2"  Liver damage from the medication
linkId: "/1/1.3"  Effects will become apparent during the study
linkId: "/1/1.4"  Yes

**(for the fifth risk):**
linkId: "/1/1.1"  Physical risk
linkId: "/1/1.2"  Cancer developing after treatment with the medication
linkId: "/1/1.3"  Effects may become apparent many years after the study
linkId: "/1/1.4"  Yes 

But, my team was under the impression that the pieces of the repeating elements would have unique link IDs assigned to distinguish each risk by its own link IDs, such as:

**(for the first risk):**
linkId: "/1_01/1_01.1"   Physical risk
linkId: "/1_01/1_01.2"   Pain from injections
linkId: "/1_01/1_01.3"   Effects will become apparent during the study
linkId: "/1_01/1_01.4"  No

**(for the second risk):**
linkId: "/1_02/1_02.1"  Physical risk
linkId: "/1_02/1_02.2"  Lowered immunity from the medication
linkId: "/1_02/1_02.3"  Effects will become apparent during the study
linkId: "/1_02/1_02.4"  Yes

**(for the third risk):**
linkId: "/1_03/1_03.1"  Psychological or Emotional
linkId: "/1_03/1_03.2"  Stress over the effects of the medication
linkId: "/1_03/1_03.3"  Effects will become apparent during the study
linkId: "/1_03/1_03.4"  No

**(for the fourth risk):**
linkId: "/1_04/1_04.1" Physical risk
linkId: "/1_04/1_04.2" Liver damage from the medication
linkId: "/1_04/1_04.3" Effects will become apparent during the study
linkId: "/1_04/1_04.4" Yes

**(for the fifth risk):**
linkId: "/1_05/1_05.1"   Physical risk
linkId: "/1_05/1_05.2"   Cancer developing after treatment with the medication
linkId: "/1_05/1_05.3"   Effects may become apparent many years after the study
linkId: "### /1_05/1_05.4"   Yes 

What is the default functionality of LHC forms for repeating elements?  Did we make an error in how we defined our form in the NLM Form Builder?  Is there any way that we can create our questionnaire in LHC forms so that the link IDs for repeating elements can have the answers appended with a suffix to make them unique?  It is very confusing to refer to JSON elements that all have the same link IDs.

**Comment by GitHubUNCStudent** [comment]
{
  "name": "Test Questionnaire Repeating Elements",
  "title": "Repeating Elements",
  "id": "355758",
  "status": "active",
  "version": "1",
  "experimental": true,
  "meta": {
    "versionId": "1",
    "lastUpdated": "2019-11-21T04:25:04.000Z",
    "profile": [
      "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire|2.7"
    ]
  },
  "items": [
    {
      "question": "Risks",
      "questionCodeSystem": "Custom",
      "questionCode": "1",
      "questionCardinality": {
        "min": "1",
        "max": "*"
      },
      "header": true,
      "editable": "1",
      "answerCardinality": {
        "min": "0",
        "max": "1"
      },
      "codeList": [
        {
          "system": "Custom",
          "code": "1",
          "display": "Risks"
        }
      ],
      "linkId": "/1",
      "items": [
        {
          "question": "What type of risk is this?",
          "questionCodeSystem": "Custom",
          "questionCode": "1.1",
          "questionCardinality": {
            "min": "1",
            "max": "1"
          },
          "header": false,
          "editable": "1",
          "answerCardinality": {
            "min": "1",
            "max": "1"
          },
          "dataType": "CNE",
          "answers": [
            {
              "text": "Psychological or Emotional",
              "code": "A",
              "label": "",
              "score": null
            },
            {
              "text": "Physical",
              "code": "B",
              "label": "",
              "score": null
            },
            {
              "text": "Financial",
              "code": "C",
              "label": "",
              "score": null
            }
          ],
          "displayControl": {
            "answerLayout": {
              "type": "COMBO_BOX"
            }
          },
          "codeList": [
            {
              "system": "Custom",
              "code": "1.1",
              "display": "What type of risk is this?"
            }
          ],
          "linkId": "/1/1.1"
        },
        {
          "question": "Describe the risk in detail",
          "questionCodeSystem": "Custom",
          "questionCode": "1.2",
          "questionCardinality": {
            "min": "1",
            "max": "1"
          },
          "header": false,
          "editable": "1",
          "answerCardinality": {
            "min": "1",
            "max": "1"
          },
          "dataType": "TX",
          "codeList": [
            {
              "system": "Custom",
              "code": "1.2",
              "display": "Describe the risk in detail"
            }
          ],
          "linkId": "/1/1.2"
        },
        {
          "question": "What is the timeline when this risk will happen?",
          "questionCodeSystem": "Custom",
          "questionCode": "1.3",
          "questionCardinality": {
            "min": "1",
            "max": "1"
          },
          "header": false,
          "editable": "1",
          "answerCardinality": {
            "min": "1",
            "max": "1"
          },
          "dataType": "CNE",
          "answers": [
            {
              "text": "Effects will become apparent during the study",
              "code": "A",
              "label": "",
              "score": null
            },
            {
              "text": "Effects may become apparent many years after the study",
              "code": "B",
              "label": "",
              "score": null
            }
          ],
          "displayControl": {
            "answerLayout": {
              "type": "COMBO_BOX"
            }
          },
          "codeList": [
            {
              "system": "Custom",
              "code": "1.3",
              "display": "What is the timeline when this risk will happen?"
            }
          ],
          "linkId": "/1/1.3"
        },
        {
          "question": "Is there a risk of death?",
          "questionCodeSystem": "Custom",
          "questionCode": "1.4",
          "questionCardinality": {
            "min": "1",
            "max": "1"
          },
          "header": false,
          "editable": "1",
          "answerCardinality": {
            "min": "1",
            "max": "1"
          },
          "dataType": "CNE",
          "answers": [
            {
              "text": "Yes",
              "code": "Yes",
              "label": "",
              "score": null
            },
            {
              "text": "No",
              "code": "No",
              "label": "",
              "score": null
            },
            {
              "text": "Unknown or N/A",
              "code": "Unknown or N/A",
              "label": "",
              "score": null
            }
          ],
          "displayControl": {
            "answerLayout": {
              "type": "COMBO_BOX"
            }
          },
          "codeList": [
            {
              "system": "Custom",
              "code": "1.4",
              "display": "Is there a risk of death?"
            }
          ],
          "linkId": "/1/1.4"
        }
      ]
    },
    {
      "question": "Procedures",
      "questionCodeSystem": "Custom",
      "questionCode": "2",
      "questionCardinality": {
        "min": "1",
        "max": "*"
      },
      "header": true,
      "editable": "1",
      "answerCardinality": {
        "min": "0",
        "max": "1"
      },
      "codeList": [
        {
          "system": "Custom",
          "code": "2",
          "display": "Procedures"
        }
      ],
      "linkId": "/2",
      "items": [
        {
          "question": "Select the type of procedure",
          "questionCodeSystem": "Custom",
          "questionCode": "2.1",
          "questionCardinality": {
            "min": "1",
            "max": "1"
          },
          "header": false,
          "editable": "1",
          "answerCardinality": {
            "min": "1",
            "max": "1"
          },
          "dataType": "CNE",
          "answers": [
            {
              "text": "Blood draw",
              "code": "A",
              "label": "",
              "score": null
            },
            {
              "text": "Xray or CT scan",
              "code": "B",
              "label": "",
              "score": null
            },
            {
              "text": "MRI",
              "code": "C",
              "label": "",
              "score": null
            },
            {
              "text": "Ultrasound",
              "code": "D",
              "label": "",
              "score": null
            },
            {
              "text": "Other lab procedure",
              "code": "E",
              "label": "",
              "score": null
            },
            {
              "text": "Injections",
              "code": "F",
              "label": "",
              "score": null
            },
            {
              "text": "Administering pills or liquid medication",
              "code": "G",
              "label": "",
              "score": null
            },
            {
              "text": "Surgery",
              "code": "H",
              "label": "",
              "score": null
            },
            {
              "text": "Usage of a medical device",
              "code": "I",
              "label": "",
              "score": null
            },
            {
              "text": "Other",
              "code": "J",
              "label": "",
              "score": null
            }
          ],
          "displayControl": {
            "answerLayout": {
              "type": "COMBO_BOX"
            }
          },
          "codeList": [
            {
              "system": "Custom",
              "code": "2.1",
              "display": "Select the type of procedure"
            }
          ],
          "linkId": "/2/2.1"
        },
        {
          "question": "How often will this procedure be done?",
          "questionCodeSystem": "Custom",
          "questionCode": "2.2",
          "questionCardinality": {
            "min": "1",
            "max": "1"
          },
          "header": false,
          "editable": "1",
          "answerCardinality": {
            "min": "0",
            "max": "1"
          },
          "dataType": "CNE",
          "answers": [
            {
              "text": "Yearly",
              "code": "A",
              "label": "",
              "score": null
            },
            {
              "text": "Several times per year",
              "code": "B",
              "label": "",
              "score": null
            },
            {
              "text": "Monthly",
              "code": "C",
              "label": "",
              "score": null
            },
            {
              "text": "2-3 times per month",
              "code": "D",
              "label": "",
              "score": null
            },
            {
              "text": "Weekly",
              "code": "E",
              "label": "",
              "score": null
            },
            {
              "text": "Daily",
              "code": "F",
              "label": "",
              "score": null
            },
            {
              "text": "Multiple times per day",
              "code": "G",
              "label": "",
              "score": null
            }
          ],
          "displayControl": {
            "answerLayout": {
              "type": "COMBO_BOX"
            }
          },
          "codeList": [
            {
              "system": "Custom",
              "code": "2.2",
              "display": "How often will this procedure be done?"
            }
          ],
          "linkId": "/2/2.2"
        }
      ]
    }
  ]
}

**Comment by plynchnlm** [comment]
In the [FHIR Questionnaire](https://www.hl7.org/fhir/questionnaire-definitions.html#Questionnaire.item.linkId) specification, the field "linkId" is defined as being unique to the item definition in the Questionnaire resource.  Therefore, if the item is a repeating group, you can expect the linkId (and the child item linkIds) to be repeated in the QuestionnaireResponse.  The structure of the group and its children are preserved, so that the each repetition's responses are grouped together in the JSON.  It is still not difficult to process.  You can see the grouping in the JSON structure of the QuestionnaireResponse link you sent:  https://lforms-fhir.nlm.nih.gov/baseR4/QuestionnaireResponse/355762/_history/1

As a side note, please make sure you have your own copies of any resources you put on lforms-fhir.nlm.nih.gov.   We reset that database typically weekly, and sometimes more often.

**Comment by GitHubUNCStudent** [comment]
Thank you for explaining how the standard LHC functionality aligns to FHIR specs.  I can work with the child items now that the team understands that this is how they are.  Thanks for the warning about the resources. I have made copies of the resources. I know that the database is refreshed often.  You can close this issue.

**Comment by plynchnlm** [comment]
You are welcome-- glad to help.
