### ISSUE TITLE
How can I send the generated QuestionnaireResponses to an online server without running in to CORS/CORB issues?

### ISSUE THREAD

**Issue by MJ422** [lhncbc/lforms#18]
I am able to successfully load a FHIR Questionnaire resource in to LForm format, using this project as a script in my web page. I can then use the LForms.Util.getFormFHIRData('QuestionnaireResponse', 'R4') method to create a QuestionnaireResponse resource. 

What can I do to send this data to an online server without running in to CORS issues? I am lost on this currently.

**Comment by MJ422** [comment]
I am able to successfully load a FHIR Questionnaire resource in to LForm format, using this project as a script in my web page. I can then use the LForms.Util.getFormFHIRData('QuestionnaireResponse', 'R4') method to create a QuestionnaireResponse resource. 

What can I do to send this data to an online server without running in to CORS issues? I am lost on this currently.

**Comment by plynchnlm** [comment]
That is a general issue that is encountered whenever you are sending data somewhere that is a different domain than the one from which the website was loaded.

The remote server needs to be configured to allow the connection.  The server should send back an Access-Control-Allow-Origin header than matches the domain of the website.  ('*' is a valid value, if you want the server to allow access from anywhere).
