### ISSUE TITLE
Ways to render a QuestionnaireResponse resource?

### ISSUE THREAD

**Issue by MJ422** [lhncbc/lforms#20]
I have been doing some practicing/testing with the various built-in methods from this project. During a collaborative meeting, one of my peers questioned if there were any possibility to render QuestionnaireResponse resources similarly to how Questionnaires are rendered as LForms.

Is there any such functionality within this project? I want to be able to display the QuestionnaireResponse resources that were generated on my app in some sort of view. 

I have attempted to pass my QuestionnaireResponse JSON data in to the "fhirToLformConversion()" method, and while it doesn't throw errors, it seems to render it as a form to add input rather than a read-only display of a QuestionnaireResponse.

I would love to know your thoughts on this, thank you so much!

**Comment by plynchnlm** [comment]
http://lhncbc.github.io/lforms/#merge-fhir-data

You'll need the Questionnaire resource as well as the QuestionnaireResponse.  First import the Questionnaire via:

var formData = LForms.Util.convertFHIRQuestionnaireToLForms(fhirData, fhirVersion)

and then merge the QuestionnaireResponse data via:

LForms.Util.mergeFHIRDataIntoLForms(resourceType, fhirData, formData, fhirVersion)

More specifically,

var formWithUserData = LForms.Util.mergeFHIRDataIntoLForms("QuestionnaireResponse", questionnaireResponseObj, formData, "R4")

You should then be able to render formWithUserData.

**Comment by MJ422** [comment]
> http://lhncbc.github.io/lforms/#merge-fhir-data
> 
> You'll need the Questionnaire resource as well as the QuestionnaireResponse. First import the Questionnaire via:
> 
> var formData = LForms.Util.convertFHIRQuestionnaireToLForms(fhirData, fhirVersion)
> 
> and then merge the QuestionnaireResponse data via:
> 
> LForms.Util.mergeFHIRDataIntoLForms(resourceType, fhirData, formData, fhirVersion)
> 
> More specifically,
> 
> var formWithUserData = LForms.Util.mergeFHIRDataIntoLForms("QuestionnaireResponse", questionnaireResponseObj, formData, "R4")
> 
> You should then be able to render formWithUserData.

Oh, awesome! Thank you. I was reading that section but was unsure if that was for rendering it. Thank you for clarifying!!

**Comment by MJ422** [comment]
Sorry, one more question..

I was able to create the "formWithUserData" object as described above, however I am a bit unclear on the rendering part. Am I to use the "LForms.Util.addFormToPage()" method to render this merged Q-QR data? 

Or is there a different paradigm to follow?

**Comment by plynchnlm** [comment]
Yes-- you would use the same API you use to render a blank form.  (addFormToPage should work.)

**Comment by MJ422** [comment]
> Yes-- you would use the same API you use to render a blank form. (addFormToPage should work.)

Thank you for your prompt replies! I will keep trying.

**Comment by plynchnlm** [comment]
I just realized all of our example apps that merge QuestionnaireResponses are using the AngularJS approach.  Here is an example on JSFiddle:  https://jsfiddle.net/lforms/y8o65qwe/7/

**Comment by MJ422** [comment]
> I just realized all of our example apps that merge QuestionnaireResponses are using the AngularJS approach. Here is an example on JSFiddle: https://jsfiddle.net/lforms/y8o65qwe/7/

I see... perhaps this is why I am not having any success 😅
Thank you for the update!

**Comment by plynchnlm** [comment]
Does the example help?  (It uses LForms.Util.addFormToPage).

**Comment by MJ422** [comment]
> Does the example help? (It uses LForms.Util.addFormToPage).

Hi there, sorry for the late response on this. 

I am unable to render all of the answer values from a QuestionnaireResponse resource, it seems to just render the questions with an answer of "valueString", but not for buttons with answer values as "valueBoolean". Any idea if there is some logic not catching these answer values in methods called within "mergeQuestionnaireResponseToLforms" function?

**Comment by plynchnlm** [comment]
I have confirmed the problem.  Could you open a new issue for this?  As a work around, you could use a list with "Yes" or "No" options.  It seems we do not handle the boolean type correctly on import.
