### ISSUE TITLE
Updated protractor tests?

### ISSUE THREAD

**Issue by dwwinters** [lhncbc/lforms#22]
Do some of the protractor tests need to be updated?  I got most working after building on a windows machine, but ran into issues with `lforms_directive_attr.spec.js`.  Specifically shouldn't the route parameters include the default hash prefix?  So [here](https://github.com/lhncbc/lforms/blob/master/test/protractor/spec/lforms_directive_attr.spec.js#L44) instead of:
```
tp.openDirectiveAttrTest('#/horizontal-form-default');
```
include a bang after the hash:
```
tp.openDirectiveAttrTest('#!/horizontal-form-default');
```
Reference: https://stackoverflow.com/questions/41226122/url-hash-bang-prefix-instead-of-simple-hash-in-angular-1-6

**Comment by plynchnlm** [comment]
We run our tests on Linux (though I can't why that should matter).  With AngularJS 1.7.9, the tests run and pass without the "!" in the URLs.

**Comment by plynchnlm** [comment]
Which browser are you using for the tests on Windows?  We are running them with Chrome.

**Comment by dwwinters** [comment]
I'm using chrome as well.  As far as I can tell you're not explicitly using [$locationProvider](https://docs.angularjs.org/api/ng/provider/$locationProvider) which is how the docs say the default prefix ("!") can be changed.  I wonder if the default behavior/settings are different on linux vs. windows?

**Comment by plynchnlm** [comment]
When I change the tests to use #!, they fail for me.   It does seem like the default is different for us for some reason.  How about making the hash prefix explicit?  Could you try modifying app/test/directiveAttrTest.html and replacing line 75 with:

75         .config(function ($routeProvider, $locationProvider) {
76           $locationProvider.hashPrefix('');

If that works for you, I will check it in.

**Comment by dwwinters** [comment]
Thanks @plynchnlm; setting the `$locationProvider` allows the check-box tests to pass for me without the bang included in the paths.  If I come across other cases like this should I report them here or in another issue?

**Comment by plynchnlm** [comment]
If you have other tests that are not passing and the reason is the same, you can report them here in this issue.  Otherwise, please create a separate issue for unrelated problems.
