### ISSUE TITLE
QuestionnaireResponse rendering broken for some item types

### ISSUE THREAD

**Issue by MJ422** [lhncbc/lforms#26]
Hi Team,

I am experiencing some issues with the QuestionnaireResponse resources being rendered in the view. 

My QR resource has answer fields filled, see below:
![image](https://user-images.githubusercontent.com/44490162/75367029-a760e680-588d-11ea-8fa5-1311f3c495dd.png)

But they are not filled when I attempt to merge the data in the QR resource with the LForm data when using _LForms.Util.mergeFHIRDataIntoLForms("QuestionnaireResponse", <qr resource>, <qr's corresponding questionnaire>, "R4")_

![image](https://user-images.githubusercontent.com/44490162/75367724-c3b15300-588e-11ea-95fa-029d828e649e.png)

@plynchnlm Please advise on where this might be going wrong. I am looking in to the  _processQrItemAndLFormsItem()_ function definition in sdc-import-common.js

**Comment by plynchnlm** [comment]
I think you are doing everything correctly, and this is a bug in lforms.  As a work around, you might try using type="choice" with answerOptions of "Yes" and "No".  Please let me know how critical this issue is for you.

**Comment by MJ422** [comment]
> I think you are doing everything correctly, and this is a bug in lforms. As a work around, you might try using type="choice" with answerOptions of "Yes" and "No". Please let me know how critical this issue is for you.

@plynchnlm Thank you for the reply. I can try to add some logic that maps your suggested syntax changes to any items that hit that bug. To do this, should I adjust the actual values in the QuestionnaireResponse resource JSON data, or in its "Lforms" version?

**Comment by plynchnlm** [comment]
To use my workaround, you would need to change the Questionnaire definition.  (You are using Questionnaire, I am assuming, and not our internal form definition format, but either way you would change the form definition.)  After that, generated QuestionnaireResponses would work when loaded back it.  However, if you have already collected QuestionnaireResponses that you want to save, this work around would require editing those into the format that matches the revised Questionnaire.   That might be a pain.

I will see if we can prioritize this, though given that we are half way through this week, chances of getting a fix out before next week are not great.  What day next week is your demo?

**Comment by MJ422** [comment]
@plynchnlm We are trying to cover this functionality before scheduling and showing it off, so let me know when you make some headway or at least find a point where you think the logic is missing and I can try to make some local changes. Thank you so much!!

**Comment by plynchnlm** [comment]
Version 21.0.1, just published, should fix this issue.
