### ISSUE TITLE
Does not support multiple default answer?

### ISSUE THREAD

**Issue by yunwwang** [lhncbc/lforms#28]
In my FHIR Questionnaire form, some open-choice questions has multiple initial answers. Example:
`
{
  "resourceType": "Questionnaire",
  "id": "1",
  "title": "Ventilator Questionnaire",
  "status": "draft",
  "date": "2020-02-04",
  "subjectType": [
    "Patient"
  ],
  "item": [
    {
      "linkId": "4",
      "text": "Patient diagnosis:",
      "type": "group",
      "item": [
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/cqf-expression",
              "valueExpression": {
                "language": "text/cql",
                "expression": "\"VentilatorDevice\".RelevantDiagnoses"
              }
            }
          ],
          "linkId": "4.1",
          "type": "open-choice",
          "repeats": true,
          "answerOption": [
            {
              "valueCoding": {
                "code": "36485005",
                "system": "http://snomed.info/sct",
                "display": "Restrictive lung disease"
              }
            },
            {
              "valueCoding": {
                "code": "G12.0",
                "system": "http://hl7.org/fhir/sid/icd-10-cm",
                "display": "Infantile spinal muscular atrophy, type I"
              }
            },
            {
              "valueCoding": {
                "code": "J98.4",
                "system": "http://hl7.org/fhir/sid/icd-10-cm",
                "display": "Other disorders of lung"
              }
            }
          ],
          "initial": [
            {
              "valueCoding": {
                "code": "36485005",
                "system": "http://snomed.info/sct",
                "display": "Restrictive lung disease",
                "_type": "Coding"
              }
            },
            {
              "valueCoding": {
                "code": "G12.0",
                "system": "http://hl7.org/fhir/sid/icd-10-cm",
                "display": "Infantile spinal muscular atrophy, type I",
                "_type": "Coding"
              }
            },
            {
              "valueCoding": {
                "code": "J98.4",
                "system": "http://hl7.org/fhir/sid/icd-10-cm",
                "display": "Other disorders of lung",
                "_type": "Coding"
              }
            }
          ]
        }
      ]
    }
  ]
}
`
After load to https://lhncbc.github.io/lforms-fhir-app/, only the first initial value is shown. 
I also checked the converted LHC form, there is only one defaultAnswer.
Is it possible to preselect multiple values for open-choice type?

**Comment by plynchnlm** [comment]
On this one, we do support it, but currently only if you supply a made-up extension.  There was some work done in October to remove this made-up extension, but somehow the task was resolved without it ever getting merged into the master branch.  We will work on getting that in.  In the meantime, as a work-around, you can include our "questionnaire-answerRepeats" extension.  This works:
```
{
  "resourceType": "Questionnaire",
  "id": "1",
  "title": "Ventilator Questionnaire",
  "status": "draft",
  "date": "2020-02-04",
  "subjectType": [
    "Patient"
  ],
  "item": [
    {
      "linkId": "4",
      "text": "Patient diagnosis:",
      "type": "group",
      "item": [
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/cqf-expression",
              "valueExpression": {
                "language": "text/cql",
                "expression": "\"VentilatorDevice\".RelevantDiagnoses"
              }
            }, {
              "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-answerRepeats",
              "valueBoolean": true
            }
          ],
          "linkId": "4.1",
          "type": "open-choice",
          "repeats": true,
          "answerOption": [
            {
              "valueCoding": {
                "code": "36485005",
                "system": "http://snomed.info/sct",
                "display": "Restrictive lung disease"
              }
            },
            {
              "valueCoding": {
                "code": "G12.0",
                "system": "http://hl7.org/fhir/sid/icd-10-cm",
                "display": "Infantile spinal muscular atrophy, type I"
              }
            },
            {
              "valueCoding": {
                "code": "J98.4",
                "system": "http://hl7.org/fhir/sid/icd-10-cm",
                "display": "Other disorders of lung"
              }
            }
          ],
          "initial": [
            {
              "valueCoding": {
                "code": "36485005",
                "system": "http://snomed.info/sct",
                "display": "Restrictive lung disease",
                "_type": "Coding"
              }
            },
            {
              "valueCoding": {
                "code": "G12.0",
                "system": "http://hl7.org/fhir/sid/icd-10-cm",
                "display": "Infantile spinal muscular atrophy, type I",
                "_type": "Coding"
              }
            },
            {
              "valueCoding": {
                "code": "J98.4",
                "system": "http://hl7.org/fhir/sid/icd-10-cm",
                "display": "Other disorders of lung",
                "_type": "Coding"
              }
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by yunwwang** [comment]
That is awesome! Thank you!
