### ISSUE TITLE
Merge QuestionnaireReponse could not hand valueDate

### ISSUE THREAD

**Issue by yunwwang** [lhncbc/lforms#29]
I met a very strange issue. I generate the LHC from from a pair of R4 Questionnarie and QuestionnaireResponse. Then I save QuestionnaireResponse from the form. Strangely the valueDate answer is missing. 
Here is the Questionnaire:
```
{
  "resourceType": "Questionnaire",
  "id": "urn:hl7:davinci:crd:ventilator-questionnaire-r4",
  "title": "Ventilator Questionnaire",
  "status": "draft",
  "date": "2020-02-04",
  "publisher": "Da Vinci DTR",
  "subjectType": [
    "Patient"
  ],
  "item": [
    {
      "linkId": "1",
      "type": "group",
      "text": "Patient Information",
      "item": [
        {
          "linkId": "1.1",
          "text": "Date of Birth:",
          "type": "date",
          "required": true
        }
      ]
    }
  ]
}
```
and here is the input QuestionnaireReponse which contains previous answer:
```
{
  "resourceType": "QuestionnaireResponse",
  "status": "draft",
  "item": [
    {
      "linkId": "1",
      "item": [
        {
          "linkId": "1.1",
          "answer": [
            {
              "valueDate": "1976-02-23"
            }
          ]
        }
      ]
    }
  ]
}
```
Here is a screen shot of generated form (the date is correct)
![image](https://user-images.githubusercontent.com/8761175/77004670-783e1200-692d-11ea-8cc8-dbc02528b782.png)
Then, I use this statement to create a QR from the form:
```
var qr = window.LForms.Util.getFormFHIRData('QuestionnaireResponse', 'R4');
```
And this is the QR created
```
{
  "resourceType": "QuestionnaireResponse",
  "meta": {
    "profile": [
      "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaireresponse|2.7"
    ]
  },
  "status": "completed",
  "authored": "2020-03-18T20:33:03.723Z",
  "item": [
    {
      "linkId": "1",
      "text": "Patient Information",
      "item": [
        {
          "linkId": "1.1",
          "text": "Date of Birth:"
        }
      ]
    }
  ]
}
```
Strangely, the answer for 1.1 is gone.
I found a solution is to actually select the date in the form, even the same date, then the date showed in the final QR.

**Comment by plynchnlm** [comment]
Thanks for this very complete bug report.   I will see if we can work on this soon.

**Comment by lhcye** [comment]
I tried the merge functions with your sample data. It seems to be working fine. 
There are 2 steps involved in the current implementation:
1) Convert the Questionnaire data to LForms : 
    lfData = LForms.Util.convertFHIRQuestionnaireToLForms( qData)
2) Merge the QuestionnaireResponse data to LForm
    mergedLfData = LForms.Util.mergeFHIRDataIntoLForms("QuestionnaireResponse", qrDat, lfData, 'R4')
Then you can get the QR again to see if it still have the valueDate:
   LForms.Util.getFormFHIRData('QuestionnaireResponse', 'R4', mergedLfData)

Let me know if you still have problems.

**Comment by yunwwang** [comment]
Here is my testing code:
```
      var lform = LForms.Util.convertFHIRQuestionnaireToLForms(qform, 'R4');
      var mergedLfData = LForms.Util.mergeFHIRDataIntoLForms("QuestionnaireResponse", savedResponse, lform, 'R4');
       var qr = LForms.Util.getFormFHIRData('QuestionnaireResponse', 'R4', mergedLfData);
```
and the qr is
```
{
  "resourceType": "QuestionnaireResponse",
  "meta": {
    "profile": [
      "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaireresponse|2.7"
    ],
    "tag": [
      {
        "display": "lformsVersion: 22.0.0"
      }
    ]
  },
  "status": "completed",
  "authored": "2020-03-19T18:02:48.020Z",
  "item": [
    {
      "linkId": "1",
      "text": "Patient Information",
      "item": [
        {
          "linkId": "1.1",
          "text": "Date Of Birth"
        }
      ]
    }
  ]
}
```
BTW, I used version 22.0.0 
```
 <script
  src="https://clinicaltables.nlm.nih.gov/lforms-versions/22.0.0/fhir/lformsFHIRAll.min.js"></script>
```

**Comment by yunwwang** [comment]
the value of mergedLfData does show the correct date:
![image](https://user-images.githubusercontent.com/8761175/77100587-e0e7c600-69e3-11ea-8b53-298b87116733.png)

**Comment by plynchnlm** [comment]
I tried your form here: https://lhcforms.nlm.nih.gov/sdc and was able to get correct responses when I saved the QR, when I loaded it back in, and when I saved it again loaded that one.

Ye noticed that the value you have in the mergedLfData is for some reason a Date object, while for him it is a string.

I am wondering if it is a browser issue.  Which web browser are you using, and which operating system?

**Comment by plynchnlm** [comment]
Here is a jsfiddle to try, which uses your test data above and version 22.0.0.  I tested it on Windows in Firefox, Chrome, and Edge, and on Linux in Firefox, and the valueData is preserved.

https://jsfiddle.net/m8xjhztw/1/

**Comment by yunwwang** [comment]
I am using Chrome 80.0.3987.149 on MacOS 10.15.3

**Comment by yunwwang** [comment]
OK. I found the problem. The QR resource I created has a Date type and after using JSON.stringify and then JSON.parse, it changes to string type. Here is the QR object (without stringify) actually looks like in my brower
![image](https://user-images.githubusercontent.com/8761175/77108171-c287c780-69ef-11ea-9d13-0c0d69c0b812.png)
And this is what the testing JSON string looks like in browser
![image](https://user-images.githubusercontent.com/8761175/77108320-f6fb8380-69ef-11ea-8502-913a9a5bfa63.png)
I add .toString() to force convert Date to string type when generating QR resource. Now it works as expected.
I don't know if you would like to fix that since I think DT type should be acceptable Date object in addition to just string text.

**Comment by plynchnlm** [comment]
You created the QuestionnaireResponse yourself, rather than asking LForms to create it?

I don't think JSON supports Date objects.

**Comment by yunwwang** [comment]
Forgot about that. :(
I have a CQL engine to pull data from EHR, and fill the Questionnaire automatically.

**Comment by plynchnlm** [comment]
Okay.  LForms supports prepopulation from Observation and Patient, and a FHIRPath engine in it, in case you weren't aware.
