### ISSUE TITLE
Does LHC forms support data type html? 

### ISSUE THREAD

**Issue by sujidivakar** [lhncbc/lforms#3]
I want to integrate my custom html field, so that I can trigger that html element.
is there any option to add custom html?

**Comment by plynchnlm** [comment]
We're not quite sure what you mean.  Do you really mean a data type of HTML (as the subject says) in the sense of the end user (filling out the form) typing in HTML as the answer to a question, or maybe entering formatted text (bold, italics, etc., with an editor, but represented internally as HTML) as the answer?  Can you provide more detail on what you are trying to do?

**Comment by plynchnlm** [comment]
Closing due to lack of response.  If you still have this question, feel free to re-open.
