### ISSUE TITLE
repeat=true/false

### ISSUE THREAD

**Issue by yunwwang** [lhncbc/lforms#31]
I tried this simple Questionnaire at https://lhcforms.nlm.nih.gov/lhcforms
```
{
  "resourceType": "Questionnaire",
  "id": "HomeOxygenTherapy",
  "status": "draft",
  "item": [
    {
      "extension": [
        {
          "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-answerRepeats",
          "valueBoolean": true
        }
      ],
      "linkId": "4",
      "text": "Patient diagnosis:",
      "type": "open-choice",
      "repeat": "false",
      "answerOption": [
        {
          "valueCoding": {
            "code": "36485005",
            "system": "http://snomed.info/sct",
            "display": "Restrictive lung disease - SNOMED - 36485005"
          }
        },
        {
          "valueCoding": {
            "code": "G12.0",
            "system": "http://hl7.org/fhir/sid/icd-10-cm",
            "display": "Infantile spinal muscular atrophy, type I - ICD-10 - G12.0"
          }
        },
        {
          "valueCoding": {
            "code": "J98.4",
            "system": "http://hl7.org/fhir/sid/icd-10-cm",
            "display": "Other disorders of lung - ICD-10 - J98.4"
          }
        }
      ]
    }
  ]
}
```
I noticed that no matter what I change the repeat, either true, false, or remove repeat elements, the form display and the QR generated are the same.
So does repeat has any effects on open-choice item?

**Comment by plynchnlm** [comment]
I see your questionnaire is using our answerRepeats extension which we removed in lforms version 23.  Which version of lforms are you using, or which of our websites are you testing against?

**Comment by yunwwang** [comment]
I am using version 22 in my program and the lhc widget website for
Questionnaire testing.

Is this fixed in version 23?

**Comment by plynchnlm** [comment]
It should be.  However, I see that neither of our demo applications has been updated to version lforms version 23.  I will reply back here when that is done.  Also, those demo applications (in the new versions which are not yet public) are using a new package called lforms-updater to try to take care of breaking changes from older form definitions (though at present it just goes back to version 21, I think).  You might wish to run lforms-updater (which has a CLI as well as an API) on your own forms before updating your program to the latest lforms version.

**Comment by yunwwang** [comment]
Thanks. I have updated my application using version 23. Works as expected on R4. Does this change also apply to STU3 (I cannot test STU3 in my current environment)?

**Comment by plynchnlm** [comment]
Both our demo apps (https://lhcforms.nlm.nih.gov/lhcforms and https://lhcforms.nlm.nih.gov/sdc) are now running LForms 23.0.1.  These can load either an STU3 or an R4 form, but you need to test STU3 you need to provide a hint that the form you are uploading is STU3.  The best way to do that is via the meta tag, like:
```
  "meta": {
    "profile": [
      "http://hl7.org/fhir/3.0/StructureDefinition/Questionnaire"
    ]
  },
```
