### ISSUE TITLE
 Bootstrap 4 migration?

### ISSUE THREAD

**Issue by BrunoGGM** [lhncbc/lforms#33]
I am developing a system with bootstrap 4 and lhc forms generates conflicts for me due to having version 3

**Comment by plynchnlm** [comment]
Thanks for letting us know about this problem.  We are planning a rewrite, and will try to avoid using bootstrap.  Unfortunately, upgrading to bootstrap 4 is not likely to be simple, and if we do that we will break things for people using bootstrap 3.  I am going to put it on our list to investigate whether we can remove bootstrap, but that would probably not happen quickly.

**Comment by BrunoGGM** [comment]
I would like to share how I made lhc forms work with bootstrap 3 and my project with bootstrap 4

I went to the location '\node_modules\lforms\node_modules\bootstrap\dist\css\bootstrap.css' and saved everything between "@font-face" and ".glyphicon-menu-up:before" class.
I removed the rest, now my project works without any problem.
