### ISSUE TITLE
if the text at the top of the section header is not populated by the user, then missing data

### ISSUE THREAD

**Issue by GitHubUNCStudent** [lhncbc/lforms#37]
I will send an email to plynchnlm  with the specifics to accompany this ticket.
This is a question about LHC Forms functionality. I don't know if it is an issue or a bug or it might be functioning as intended.

For the Assessments section  and the Risks section of our questionnaire, if the text at the top of the section header is not populated by the user but the user populates the rest of the section, the following is noted:

A.  The FHIR questionnaire response does not contain the answers from the user.
B.  Of course, the database does not contain the answers from the user

Please see the attached screen shots for what I am referring to as the "text at the top of the section".

Is this normal behavior of LHC Forms?

**Comment by GitHubUNCStudent** [comment]
![Risks screen shot](https://user-images.githubusercontent.com/53313544/81130820-1e160200-8f17-11ea-8738-b5df416d357a.png)
![Assessments screen shot](https://user-images.githubusercontent.com/53313544/81130821-1eae9880-8f17-11ea-90de-9eaf19692a73.png)

**Comment by plynchnlm** [comment]
I think that is bug in LHC-Forms (lforms), which we will fix.  However, In the form you are showing a picture of, I wonder whether you need that answer field for the "Assessments" item.  If you set the item type to "group", that question field will go away, and so will the problem.

**Comment by GitHubUNCStudent** [comment]
I don't know if this question is needed or not.   To me, it doesn't seem to be collecting any useful data, but there might be some intended purpose that I have not be informed of.  Thanks for the idea of changing the item type if the question is not necessary. I will discuss all of this with the questionnaire designer.

Diane Rodden
MSIS candidate Spring 2020
School of Information and Library Science UNC-CH
Summer 2019-Spring 2020 intern at Duke CTSI


________________________________

**Comment by plynchnlm** [comment]
This issue should be fixed now by version 24.1.4.
