### ISSUE TITLE
 How to validate the form data before sending and displaying errors?

### ISSUE THREAD

**Issue by BrunoGGM** [lhncbc/lforms#40]
Hello, how can I validate the form data before sending and displaying errors?

**Comment by plynchnlm** [comment]
We don't have an API method for validating the form's data.  You could check for certain classes on the fields to know whether we think the field is invalid or missing.  We should probably add an API call to check whether anything in the form is flagged as invalid.

**Comment by BrunoGGM** [comment]
> We don't have an API method for validating the form's data. You could check for certain classes on the fields to know whether we think the field is invalid or missing. We should probably add an API call to check whether anything in the form is flagged as invalid.


Are you working on something? Any way to support the project to be able to integrate that function? I am interested in supporting it in some way :)

**Comment by BrunoGGM** [comment]
I have reviewed the documentation for the most recent versions and I see that there is already a function for that, thank you very much for your work. Still I am interested in knowing how it works in the project and being able to help add new functions

**Comment by plynchnlm** [comment]
Yes, sorry I did remember to return to this issue to make at note that we had added a validation API (https://lhncbc.github.io/lforms/#validation).  There are currently a couple of bugs with it for date and time fields.   Contributions via pull requests would be welcome.

**Comment by plynchnlm** [comment]
I should have mentioned that if you do plan to contribute something, it would be best to let us know in advance so we might coordinate.
