### ISSUE TITLE
Support for EnableWhenExpression not found ..

### ISSUE THREAD

**Issue by sravanthy** [lhncbc/lforms#48]
In Lforms enableWhenExpression extension support is not added.Please assist..

**Comment by plynchnlm** [comment]
Correct.  It is on our list to add, and should not be too difficult to do, I think, but it is a matter of priorities.  Do you have an urgent need for it?

**Comment by djvreeman** [comment]
I'd love to see this feature added as well. We have a couple of forms that it'd be nice to program with logic to enable questions based on launch context variables (age, sex).

**Comment by plynchnlm** [comment]
I am hoping to get to this in the next month.  In the meantime, a workaround would be to use calculatedExpression on a hidden field, and then use enableWhen based on the calculatedExpression field value.

**Comment by plynchnlm** [comment]
enableWhenExpression is now available in version 29.3.0.
