### ISSUE TITLE
Lform API Documentation

### ISSUE THREAD

**Issue by TiLegend** [lhncbc/lforms#5]
Hi could you share link to API documentation. Also Is this project suspended??

**Comment by plynchnlm** [comment]
The project is still active.  I'm sorry we missed your earlier question.  The documentation is here:

http://lhncbc.github.io/lforms/

**Comment by TiLegend** [comment]
Thanks, I found it before. Is there an API for exporting a filled  form? or should use data from  window.loincData and convert it other way

**Comment by TiLegend** [comment]
Also I found some bugs in the form constructor.

**Comment by TiLegend** [comment]
**plynchnlm ** Thank you. Could you write to tilegenjuban@gmail.com or give your email for cooperation

**Comment by plynchnlm** [comment]
Done.
