### ISSUE TITLE
Decimal question type returns no answer property when 0 is enterred

### ISSUE THREAD

**Issue by drbobpratt** [lhncbc/lforms#53]
I have a form in which I have several decimal types. when a 0 is entered, as shown, the response item has no answer proprty. 0 should be a valid value. 
![image](https://user-images.githubusercontent.com/5684394/107528545-f891e500-6b87-11eb-9f31-6d02a38a3ce7.png)
![image](https://user-images.githubusercontent.com/5684394/107528583-034c7a00-6b88-11eb-9d6f-c1f6040a214e.png)

**Comment by plynchnlm** [comment]
That problem was fixed recently, in version 27.1.1.  Which version are you using?

**Comment by drbobpratt** [comment]
Thanks for the response. I noticed just today that I am a couple versions down (26.3.1). Updating to 28.1.0 and will check out this fix.

**Comment by drbobpratt** [comment]
Confirmed in 28.1.0.  Thanks for the response.

**Comment by plynchnlm** [comment]
Glad to hear it.
