### ISSUE TITLE
Can form be rendered with no indentation markers

### ISSUE THREAD

**Issue by drbobpratt** [lhncbc/lforms#54]
I would like the form rendered with no side markers at all. I found the template option to not use tree view, but really want nothing on the left. Is this possible ?

![image](https://user-images.githubusercontent.com/5684394/107529159-971e4600-6b88-11eb-8a89-e9c7e1c3a210.png)

currently using these settings
lformsQ.templateOptions = {
      showFormHeader: false,
      hideFormControls: true,
      useTreeLineStyle: false,

**Comment by plynchnlm** [comment]
We don't support that currently, though we are working on a rewrite which will have that feature.  That is a few months away, I think.  In the meantime, our only suggestion is that you might able to override the CSS properties for those bars.  I suspect it would be easier to do it for the bars than for the tree lines.
