### ISSUE TITLE
Validation on hidden/disabled fields

### ISSUE THREAD

**Issue by malco21** [lhncbc/lforms#59]
Required fields that are disabled via the "enableWhen" property are throwing validation errors when empty (LForms.Util.checkValidity() response). No validation should be applying to these fields when hidden. 
Here is the form I'm working on with a bunch of conditional fields: https://jsfiddle.net/ryfgek6n

Thanks.

**Comment by plynchnlm** [comment]
Thanks for this report and for the example.  It will probably take us 2-3 weeks to get a fix out.  If you need something sooner, I could probably tell you exactly what to change in the code, but you would have to build the package from the source.

**Comment by malco21** [comment]
Thanks but I don't need a fix asap (we aren't live with anything yet). I appreciate you looking into this.

**Comment by plynchnlm** [comment]
This is fixed in 29.0.3.  Thanks for reporting the issue.
