### ISSUE TITLE
AutoComplete example using LOINC API not working for recent versions.

### ISSUE THREAD

**Issue by Matt2012** [lhncbc/lforms#67]
`Uncaught ReferenceError: Def is not defined`

```
var ac = new Def.Autocompleter.Search('loinc_item',
  'https://clinicaltables.nlm.nih.gov/api/loinc_items/v3/search?type=form&available=true', {
    nonMatchSuggestions: false
  });
```

Example 13 not working for versions over about 13.
https://lhncbc.github.io/lforms/demos.html

**Comment by plynchnlm** [comment]
Thanks for reporting that.  The "Def" namespace was moved inside the LForms namespace, so just replace "Def" with "LForms.Def" in both places in that demo.  https://jsfiddle.net/786zg4hu/

I will leave this open until we update the demo in the documentation.

**Comment by plynchnlm** [comment]
The demo is updated and fixed.
