### ISSUE TITLE
demo with angular instead of Purejs

### ISSUE THREAD

**Issue by dbruinsma** [lhncbc/lforms#7]
Would it be possible to provide an example similar to demo page that works when you change the framework to "Javascript + AngularJS" ?

Thanks

![image](https://user-images.githubusercontent.com/23061924/53906947-207e8280-401a-11e9-850b-386f417064d7.png)

**Comment by lhcye** [comment]
You might take a look at https://github.com/lhncbc/lforms-fhir-app and https://github.com/lhncbc/formbuilder-lhcforms.

They both LForms widget and AngukarJS.

**Comment by plynchnlm** [comment]
Also, the lforms package itself comes with some test pages which use the AngularJS directive.  Those are under app/test.  (You might look at app/test/directiveTest.html.)  You can run those if you clone the repository, run "grunt build", and then "grunt serve".

**Comment by plynchnlm** [comment]
Closing due to lack of response.
