### ISSUE TITLE
Empty objects when extracting data from a CNE field that was prefetched with the autocomplete-lhc lib 

### ISSUE THREAD

**Issue by Harown** [lhncbc/lforms#75]
Please see: https://jsfiddle.net/3rndypj9/
It's a form with a CNE question. When selecting some items and calling _LForms.Util.getFormData_ the value contains an array with empty objects:
![image](https://user-images.githubusercontent.com/28299979/141475535-8475c559-125d-4165-911c-3cb13bfe12a7.png)

When changing the dataType to "CWE" the array contains the selected display values: 
![image](https://user-images.githubusercontent.com/28299979/141475416-0c20a91d-de85-425e-8490-be02669846e7.png)

Some questions:
1. Is this a bug?
2. Is it possible to also include the code and not only the display code in the response?
3. Why is it possible to select more values as configured in _maxSelect_?
4. Do I use the autocomplete-lhc wrong? There are two spans with _class="autocomp_selected"_ and so there are two borders:
![image](https://user-images.githubusercontent.com/28299979/141475062-bc6b64c1-5564-4176-87cd-cfde05efd003.png)
![image](https://user-images.githubusercontent.com/28299979/141475662-12dc4407-98ce-442b-9207-8a6cde5f7b4f.png)

Thanks a lot!

**Comment by plynchnlm** [comment]
I am pretty sure that the problem is that answer list is not defined in the form definition, but in your example you have created that separately.  Please see https://jsfiddle.net/lforms/v0uo9kam/ for an example of how to define an answer list, if you modify your example to do it that way and still have issues, feel free to reopen this.

**Comment by Harown** [comment]
Thank you :)
Problem is: The answer list can be dynamic (and is very long) but the questionnaire definition shall be relatively constant. Thus, the idea to use the autocomplete-lhc lib and to not define the answer list in the questionnaire. But this is not achiveable then, I guess?

**Comment by plynchnlm** [comment]
Sorry I missed this earlier.  You can have dynamic lists.  See http://lhncbc.github.io/lforms/demos.html, Demo 6, "AJAX autocompletion fields".

**Comment by Harown** [comment]
Thanks. That's the way I implemented it in the meantime. Works perfectly. :)
