### ISSUE TITLE
Load issue for around 15 minutes during child item creation.

### ISSUE THREAD

**Issue by srikala510** [LHNCBC/lforms#76]
I imported a 378 KB json file into Form Builder and proceeded to add child items for few rows. In the beginning it went on without much delay. But after 5 minutes, loading issues were seen during creation of each child item (around 15 minutes). Even after creation of child item, the page remains unresponsive for some more time. Exporting the file to save data also becomes tedious since every step takes more than 5 minutes to work. Is there a solution for this?
![LHC Github issue](https://user-images.githubusercontent.com/91660171/143003047-0c6b3fcb-e081-483e-a8ba-bd01b0bd5d9e.jpg)

**Comment by plynchnlm** [comment]
We are not sure what is causing the problem for your particular form, but we are aware of some performance issues (though not to that extent) with very large forms.  We are close to releasing a new version of the Form Builder which should not have those (known) performance issues.  One idea have as a work around in the meantime is that if the form was working fine for several minutes, you might get by if you save for the form every few minutes, reload the form builder, and then reload the form.  Another idea is that you could edit the form in sections, and then manually paste the form items together when done.   Hopefully in few weeks the new form builder will be out.

**Comment by plynchnlm** [comment]
Please try the new version (released some time ago) at https://lhcformbuilder.nlm.nih.gov/, and open a new ticket in the [formbuilder](https://github.com/LHNCBC/formbuilder-lhcforms) repository if you still see the problem.
