### ISSUE TITLE
Does LHC form autofill the all content on focus using externallyDefined URL

### ISSUE THREAD

**Issue by Ajmal-M-A** [lhncbc/lforms#8]
Created a CWE type Item with externallyDefined Url as data. It appears as search box appear the results while typing.

We need to show all options from the url when  focus input first time (prefetch AJAX autocompleter). Is it available now?

**Comment by plynchnlm** [comment]
When externallyDefined is set, it uses a search AJAX autocompleter.  That is designed for large lists, in which case our thought was that it does not make sense to show 7 results out of 5000, if no search string was provided.

For short lists, a prefetch autocompleter is used but it is not AJAX.  The "prefetch" part means it is loaded with the [form definition](https://github.com/lhncbc/lforms/blob/master/form_definition.md) in items.answers.  Would that work for you?  How long is your list?

**Comment by Ajmal-M-A** [comment]
Hi @plynchnlm, My list is short (May be around 10-15) , But it is dynamic. Need to be controlled (Can add/delete the items from the backend). So a prefetch autocompleter with AJAX required.

**Comment by plynchnlm** [comment]
By "dynamic", do you mean that the list needs to update while the user is using the form?  If not, one option for you would be to generate/update the form definition before rendering it.

I think the easiest way to add support for this would be to provide an option for search lists to show the first few items of the list when the field was focused, even before the user typed.  This would mean AJAX requests for each keystroke in the field, but would less disruptive than adding an mechanism to load external prefetch lists in via AJAX.

It will probably be a few weeks before we can get to that.

As a work around, if you have the field set up as a search list (with externallyDefined), then you could add some JavaScript to the page in an onfocus event handler for the list field that would trigger a search, e.g.:
$('#list_field_id')[0].autocomp.runSearch() should cause the list to show.

**Comment by Ajmal-M-A** [comment]
Thanks @plynchnlm. `$('#list_field_id')[0].autocomp.runSearch()`  worked.
