### ISSUE TITLE
Building and deploying to Azure Web Services (Windows)

### ISSUE THREAD

**Issue by TerriblyVexed** [lhncbc/lforms#85]
Sorry if this is a noob question (I'm new to web sites in general and Angular specifically).
I have created a solution in Visual Studio 2019. That is our standard deployment, code management, ftp client, development suite. I've seen a demo where this gets deployed successfully to Azure Web Services using Visual Studio Code, but I would prefer to use VS proper. 
To that end I created a new project using ASP.net Core with Angular template. I built it and deployed it to my site. Hello World works fine.
I then exit VS and add the lforms code files. I tried adding them to ClientApp and root directories. Open VS, npm install, ng build, IIS Express, runs fine locally. I import my sites publish profile and try to Publish. It gets through the initial process but bombs out on lines 32 and 33 of package.json b/c they are Linux commands. I update them to Windows equivalents, npm install, ng build, build solution, and attempt to Publish again. It gets past 32 and 33 but then fails on 34.
Is there a Windows translator or version of the software? 
I don't understand why I can run it fine locally on Windows.
I don't understand when VS Publishes why it affects local files and directories, for instance dist; I thought the Publish executes against the Azure Site?

**Comment by plynchnlm** [comment]
We are not using Azure, so I am not sure we offer help on that front.  I am sorry about the Linux commands in package.json.  We were trying to avoid that, but some slipped in.  Can you tell us which version of lforms you are using?  The line numbers of the commands in package.json will likely differ between versions.

**Comment by TerriblyVexed** [comment]
30.0.0-beta.7

**Comment by plynchnlm** [comment]
In that version, line 34 is the command "node prepare-zip.js".  What issue does that have on Windows?  Is node in your %PATH%?  I can see the problems with 32 and 33, which we will address.

**Comment by plynchnlm** [comment]
Also note that if you are not trying to customize this package, you can use the prebuilt versions at https://clinicaltables.nlm.nih.gov/lforms-versions

**Comment by TerriblyVexed** [comment]
Thanks for your help

Ma bad...
It's line 35. It gives a syntax error. Seems to have issue with the variables. $npm_package_name $npm_package_version. I changed them to %npm_package_name% and %npm_package_version%. I'm not sure it worked. So I replaced them with hard coded values and replaced the semicolon with &&. Still errors with no clue what the error might be.

[2022-02-24T20_16_37_920Z-debug.log](https://github.com/lhncbc/lforms/files/8135475/2022-02-24T20_16_37_920Z-debug.log)
![Capturelformserror](https://user-images.githubusercontent.com/25827884/155601601-96724b05-f2e6-4c2f-a03c-bd5a0196cd5b.PNG)

Also I note that the directory structure seems to be off. In package.json
"main": "dist/index.js"
That doesn't exist. Presumably when the scripts work it creates dist/lforms-30.0.0-beta.7, right? But I've never seen that directory either. I've only ever seen dist/webcomponents which gets created on a successful local build.
In tsconfig.json
"outDir": "./dist/out-tsc"
Also doesn't exist.
In angular.json
"outputPath": "dist/webcomponent"
Does exist when build locally. 
In package.json
line 35 "build:zip": "cd dist && dirname=lforms-30.0.0-beta.7 && zip -r $dirname.zip $dirname && mv $dirname lforms",
This does a move and rename right? Ultimately should there be a structure of dist/lforms?

Thanks for the link, but I'm afraid IDK what to do with it. Surely I'm not meant to click each file and copy it locally.

**Comment by plynchnlm** [comment]
dist/index.js is created if your build successfully completes, as will dist/lforms.

The issue on line 35 is that your Windows system probably does not know the "zip" command.  The error you pasted above is because Windows doesn't understand -p as an option for mkdir.

The link is to a place where you can download the prebuilt files for each version.  If you scroll down past the folders, you will see zip files for each version, e.g. https://clinicaltables.nlm.nih.gov/lforms-versions/lforms-30.0.0-beta.7.zip.

**Comment by TerriblyVexed** [comment]
Ah thanks for the tip on the zip. lol. That worked.

I managed to get passed line 33 with
"build:mkdist": "md dist && md dist\\lforms-30.0.0-beta.7 && shx cp src/index.js dist\\lforms-30.0.0-beta.7",

I got passed line 35 with
"build:zip": "cd dist && tar -a -c -f lforms-30.0.0-beta.7.zip lforms-30.0.0-beta.7 && move /y lforms-30.0.0-beta.7 lforms",

I tried to run build:fhir and got stuck at line 36
"build:version": "node -e 'require(\"fs\").writeFileSync(\"src/version.json\", JSON.stringify({lformsVersion: require(\"./package.json\").version}))'",

**Comment by plynchnlm** [comment]
That line is pure Node.js.  Is node in your PATH?

**Comment by TerriblyVexed** [comment]
It is.
The fix was adding escaped quote marks around the script
"build:version": "node -e \"'require(\"fs\").writeFileSync(\"src/version.json\", JSON.stringify({lformsVersion: require(\"./package.json\").version}))'\"",

The Publish has completed! 

But the site doesn't load.
 An unhandled exception was thrown by the application.
System.InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.
Your application is running in Production mode, so make sure it has been published, or that you have built your SPA manually. Alternatively you may wish to switch to the Development environment.

My guess is I made a change somewhere to index.html that is not correct.

**Comment by TerriblyVexed** [comment]
When the site is deployed it is deployed to ClientApp/dist/webcomponent at the /site/wwwroot/ correct? But the Startup.cs says
// This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllersWithViews();
            // In production, the Angular files will be served from this directory
            services.AddSpaStaticFiles(configuration =>
            {
                configuration.RootPath = "ClientApp/dist";
            });
        }

Shouldn't that RootPath include /webcomponent? The reason I ask is b/c I'm getting that could not find /index.html error. But I don't know if it starts at ClientApp/dist and looks for index.html recursively or it needs to be specified. Can you help? Does the app also need access to the dist/lforms directory? So if I set it to dist/webcomponent will it then "miss" dist/lforms?

**Comment by TerriblyVexed** [comment]
What is the entry point document for this?
I see in package.json:
"main": "dist/index.js",
Yet when the build is run there is no such file.
"build:mkdist": "md dist && md dist\\lforms-30.0.0-beta.7 && shx cp src/index.js dist",
that copies it into dist, but then when 
"build:lforms": "ng build --prod --extra-webpack-config webpack.lforms.extra.config.js && node concatenate.js",
runs it seems to remove it.
Also it is not present in the zip file or the /dist tree.

Can this be deployed to IIS? If so, how?

**Comment by plynchnlm** [comment]
Sorry for the delay.  I have been getting flooded by GitHub notifications, and only small percentage are actually from users or otherwise useful, so I missed your earlier messages, but I have read them now.  From these messages it sounds like you might be thinking lforms is an app?  I assume you have looked at https://lhncbc.github.io/lforms/, which is out of date for these beta releases you are trying, but the LForms.Util.addFormToPage function is still the way to add use the the library to add a form to your page.  The reason I am asking is that your questions about publishing to IIS and index.html are issues for an application or website, and this package is just a widget meant to be used within some application which you would write.  See the demos page at https://lhncbc.github.io/lforms/demos.html for minimal examples for the non-beta versions.  We'll be publishing documentation and demos for the beta version once we resolve a few more issues.

**Comment by TerriblyVexed** [comment]
Yes I was intending the use to be app-like. I’ll be calling it from an iFrame in another site.
So the apron h I was taking was that it would be deployed as an Angular single page site using ASP.NET. I have worked through almost all the issues associated with this approach. Publishing from Visual Studio is a bit hit or miss at the moment but it does deploy. I’ve added index.html and web.config file s to the root of my site but I’m having issues with the test page calling the .js files. I had the console on Chrome open and the Log Stream on Azure and between the two have gotten the site to load. But when I select a Questionnaire from the drop down and click Load Form nothing happens. It’s giving an error about syntax at line 1 position 1 ‘<‘. So I think it’s returning error messages in JSon but interpreting the JSON as an error b/c it’s expecting text/html Content-Type.

**Comment by TerriblyVexed** [comment]
Or, you know, the reverse of that. Apparently, in addition to being shite at websites, I’m also dyslexic.

**Comment by TerriblyVexed** [comment]
I’m not only the lysdexic club present but I’m also a clown.

**Comment by plynchnlm** [comment]
Don't be so hard on yourself.  Web development (and Angular in particular) is complicated.  If you just trying to render a form using our package, this JsFiddle might be a good starting point:  https://jsfiddle.net/lforms/8f754jhy/36/

**Comment by TerriblyVexed** [comment]
So there were multiple pathing issues. I worked with another developer and they have all been resolved. Example ../styles.css changed to /dist/webcomponent/styles.css. Also a couple cases of src="" had to be changed to href="".
But it is now running.
