### ISSUE TITLE
 Form builder in local environment

### ISSUE THREAD

**Issue by BrunoGGM** [lhncbc/lforms#87]
Hello, I have a question and I hope you can help me solve it.
I would like to know if it is possible to have a Form Builder like the one at: https://lhcformbuilder.nlm.nih.gov/ and be able to create the forms on my server without depending on any external page.

In addition to being able to work with my own database

Thanks and regards.

**Comment by plynchnlm** [comment]
The repository for the form builder is https://github.com/lhncbc/formbuilder-lhcforms.  The version that is like  https://lhcformbuilder.nlm.nih.gov/ is 6.5.x.  The 7.x.x is a new version on which we are still fixing bugs.
