### ISSUE TITLE
Contributions in the project

### ISSUE THREAD

**Issue by BrunoGGM** [lhncbc/lforms#88]
Hello again

I have been working with the tool for at least a year, I have seen in several comments that contributions are welcome, but I would like to know if you have any task lists or road maps to know what you are working on so I can help.

I have read that one of the most requested features is translation, I would like to help with that.

Greetings

**Comment by plynchnlm** [comment]
Thanks for offering.  Our "to do" list is mostly focused on things to a support for [FHIR Questionnaires](https://www.hl7.org/fhir/questionnaire.html) and the [Structured Data Capture Implementation Guide](https://build.fhir.org/ig/HL7/sdc/).  You can see our support (and the "not yet supported" sections) at https://github.com/lhncbc/lforms/blob/master/r4-support.md and https://github.com/lhncbc/lforms/blob/master/sdc-support.md.

If by "translation" you mean translations of form data, that is area still being [worked out](https://chat.fhir.org/#narrow/stream/179255-questionnaire/topic/multi-language.20questionnaires) for FHIR, and has an [open FHIR issue](https://jira.hl7.org/browse/FHIR-32379), so we would probably wait to implement something until it was proposed as a standard.  You would be welcome to participate in those discussions.

On the other hand, if what you mean is translating various English labels on buttons (e.g. "Add another") and tooltips, that could be done, and I would be interested in hearing what your thoughts are about how you would do that.

Feel free to email me at plynch@mail.nih.gov

**Comment by BrunoGGM** [comment]
@plynchnlm hi!, I send an email from bruno.gomez(at)cares.com as you suggested, I am interested in contributing.

**Comment by BrunoGGM** [comment]
I hope to get an answer from you, thank you and good day.

**Comment by plynchnlm** [comment]
Sure!  I have not gotten an email from you yet.  I checked our spam quarantine and I don't see it there either.

**Comment by plynchnlm** [comment]
Okay, I found your email.
