### ISSUE TITLE
LhcFormComponent preprop's property isn't preventing expression-based population

### ISSUE THREAD

**Issue by alexdefelipe** [lhncbc/lforms#89]
I'm loading a FHIR Questionnaire that is configured with expression-based population, and this mechanism should be launched under certain conditions. However, population is still carried out despite explicitly setting **LhcFormComponent preprop's** flag to **false**. Is it possible that this population mechanism is always carried out and that the flag only controls observation-based population?

I've updated to [pastebin](https://pastebin.com/SHAi9Zrt) the questionnaire I'm using.

**Comment by plynchnlm** [comment]
It looks like you are expecting initialExpression to not run under some circumstances.  You are right that the prepop flag does not control that.  What is the case where you do not want initialExpression to run?  The only case where I am aware it shouldn't run is if you are showing saved data from a QuestionnaireResponse.  We recently fixed a bug in which initialExpression was running in that case. If that is the problem you are seeing, which version are you using?

**Comment by alexdefelipe** [comment]
Yes, that's the case I'm working on. I was using version 30.0.0-beta.8, but I've changed to 30.0.0-beta.9 and I'm not experiencing the issue anymore. Thank you!
