### ISSUE TITLE
observationExtract mechanism is extracting data from hidden answers

### ISSUE THREAD

**Issue by alexdefelipe** [lhncbc/lforms#91]
I've developed [this questionnaire](https://github.com/lhncbc/lforms/files/8334113/qpruebaextract.txt) with some items configured to be conditionally displayed. I expected the observationExtract mechanism to create observation only for displayed items but is not. For this submission:

![image](https://user-images.githubusercontent.com/2099605/159722877-92ab9b03-ef0d-4dbe-bb37-8a7223ede2e5.png)

I get two resources for the single-displayed questionnaire:

![image](https://user-images.githubusercontent.com/2099605/159723012-7991f6bb-3106-4e5a-a6ab-4098eda1f3a6.png)

I've only tested with items of type _choice_ with a default value, and I guess the problem might be here... although some items are not being displayed, they've already got a value for the item's value property. Then, when calling  _LForms.Util.getFormFHIRData_, it checks that they are marked for extraction and that they've got a value, and an observation for each of them is generated. 

Moreover, there's a second issue with the extracting mechanism: no observation is generated for the unique displayed item. The two observations are from the hidden items. I guess this is due to the fact that its value is false, which seems to skip the generation mechanism:

![image](https://user-images.githubusercontent.com/2099605/159725613-89c512e4-c4d6-4ea6-9311-7958f1891020.png)

**Comment by plynchnlm** [comment]
Thanks for the report.  We will try to get to this soon.

**Comment by alexdefelipe** [comment]
I've checked out that version 30.1.2 solved all the pointed-out issues. Thank you! However, I've noticed another one: no observations are created for boolean items initialized to false that are untouched. To create a false-valued observation, I have to mark it first as true and then as false.

**Comment by lhcye** [comment]
I have identified the problem. We will get it fixed in the next release.

**Comment by plynchnlm** [comment]
It might not be the very next release, because we are working on another issue as well.

**Comment by plynchnlm** [comment]
This should now be fixed in 30.1.4.
