### ISSUE TITLE
react installation

### ISSUE THREAD

**Issue by okongwu101** [lhncbc/lforms#95]
I have tried to install the widget in a react application. I keep getting errors that LForms is undefined when i run 
LForms.Util.addFormToPage(formDefinition, 'myFormContainer', options);.

Can anybody give me an idea on how to install the widget in react effectively? Thanks in advance.

**Comment by plynchnlm** [comment]
I don't know if you saw my reply to your comment on the other issue:

@lhcye Created this example of a React app using the lforms webcomponent (version 30.3.0): https://codepen.io/lhcye/pen/KKQbbwZ

**Comment by okongwu101** [comment]
> I don't know if you saw my reply to your comment on the other issue:
> 
> @lhcye Created this example of a React app using the lforms webcomponent (version 30.3.0): https://codepen.io/lhcye/pen/KKQbbwZ

Sorry i created this issue before i saw the other... Will close it after this.
